#!/usr/bin/perl

$searchDir="$ENV{JSFROOT}/src  $ENV{LEDAROOT}/src $ENV{URANUSROOT}/src $ENV{SATELLITESROOT}/src ";
open(FOUT,"> makeclass.C ");

print FOUT "int makeclass() {\n";

open(FIN,"grep -Hhr \"#pragma\" $searchDir | grep C++ |");
while( <FIN> ) {
 ($fname,$line)=split(":");
 next if ( $fname =~ /template/ );
  next if ( $line =~ /^\/\// ) ;
  @cname=split(" ");
  $classname=$cname[4];
  $classname=~s/;//g;
  $classname=~s/\+//g;
  $classname=~s/\-//g;
  next if ( $classname =~ /^U4CDC/ );
  next if ( $classname =~ /^S4CDC/ );
  next if ( $classname =~ /^S4Baby/ );
  next if ( $classname =~ /^U4Baby/ );
  next if ( $classname =~ /^Baby/ );
  next if ( $classname =~ /^Baby/ );
  next if ( $classname =~ /JIM/ );
  next if ( $classname =~ /VUserAnalysis/ );
  next if ( $classname =~ /UserAnalysis/ );
  next if ( $classname =~ /U4VAnalysis/ );
  next if ( $classname =~ /JSFHelixErrorMatrix_u/ );
  
  print FOUT "   myhtml.MakeClass(\"",$classname,"\");\n";
  print $classname,"\n";
}

print FOUT "}\n";

close(FOUT);
close(FIN);


